import { Box, Flex, Input, Text, Stack, Show, Image } from '@chakra-ui/react'
import Head from 'next/head'
import { useState, useEffect } from 'react'
import { Banner } from '../../components/Banner'
import Navbar from '../../components/Navbar'
import getPhoto from '../services/axios'

type IHit = {
  webformatURL: string;
  likes?: number ;
}

type IHits = {
  hits: IHit[];
  total: number;
  totalHits: number;
}

export default function America(){
  const [imagesUrl, setImagesUrl] = useState<IHits | null>();

  useEffect(() => {
    const getNewPhoto = async (pesquisa: string) => {
    const photos = await getPhoto(pesquisa);
      
    setImagesUrl(photos);
    console.log(photos);
    console.log(imagesUrl?.totalHits);
    }

    getNewPhoto("america sightseeing");
    
  },[]);

  return (
    <div>
      <Head>
        <title>WorldTrip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/airplane.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <Navbar />
        <Banner bg="America.jpg" text = "America"/>
        <Flex  justifyContent="center" alignItems={"center"} bg="white">
          <Stack direction={'row'}
            justifyContent="center"
            alignItems="center"
            spacing={'45px'}
          >
            <Show above='sm'>
              <Text justifyContent="space-between" color='dark.headtext' w={'600px'} fontSize='24'>
              Um continente de grandes belezas:
              América é o segundo maior continente em área, localizado no hemisfério ocidental e que se
              estende, no sentido norte-sul, desde o oceano Ártico até o cabo Horn, ao longo de cerca de
              15 mil quilômetros.

              </Text>
              <Stack justifyContent="center" alignItems={"center"} >
                <Text as='b' color='highlight50' fontSize='48'>
                  35
                </Text>
                <Text as='b' color='dark.headtext'>
                  países
                </Text>
              </Stack>
              <Stack justifyContent="center" alignItems={"center"} >
                <Text as='b' color='highlight50' fontSize='48'>
                  1061
                </Text>
                <Text as='b' color='dark.headtext'>
                  línguas
                </Text>
              </Stack>
              <Stack justifyContent="center" alignItems={"center"} >
                <Text as='b' color='highlight50' fontSize='48'>
                  20
                </Text>
                <Text as='b' color='dark.headtext'>
                  cidades +100
                </Text>
              </Stack>
            </Show>
          </Stack>

          <Stack direction={'column'}
            justifyContent="center"
            alignItems="center"
          >

            <Show below='sm'>
              <Text justifyContent="space-between" color='dark.headtext' w={'340px'} fontSize='14'>
                A Europa é, por convenção, um dos seis continentes do
                mundo. Compreendendo a península ocidental da Eurásia,
                a Europa geralmente divide-se da Ásia a leste pela
                divisória de águas dos montes Urais, o rio Ural, o
                mar Cáspio, o Cáucaso, e o mar Negro a sudeste
              </Text>
              <Stack direction={'row'} spacing={'40px'}>
                <Stack justifyContent="center" alignItems={"center"} >
                  <Text as='b' color='highlight50' fontSize='32'>
                    50
                  </Text>
                  <Text color='dark.headtext'>
                    países
                  </Text>
                </Stack>
                <Stack justifyContent="center" alignItems={"center"} >
                  <Text as='b' color='highlight50' fontSize='32'>
                    60
                  </Text>
                  <Text color='dark.headtext'>
                    línguas
                  </Text>
                </Stack>
                <Stack justifyContent="center" alignItems={"center"} >
                  <Text as='b' color='highlight50' fontSize='32'>
                    27
                  </Text>
                  <Text color='dark.headtext' >
                    cidades +100
                  </Text>
                </Stack>
              </Stack>
            </Show>
          </Stack>
          <Image m={1} src='/icon_Info.png' w={[3, 4]} pt={[52, 80]} />
        </Flex>
      </main>
    </div>
  )
}
