import { Flex, Text, Stack, Show, Image, Grid } from '@chakra-ui/react'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Banner } from '../components/Banner'
import Navbar from '../components/Navbar'
import { Card_cidades } from '../components/Card_cidades'
import getPhoto from '../services/axios'

type IHit = {
  webformatURL: string;
  likes?: number;
}

type IHits = {
  hits: IHit[];
  total: number;
  totalHits: number;
}

export default function Europa()
{
  const [imagesUrl, setImagesUrl] = useState<IHits[] | null>();

  useEffect(() =>
  {
    const getNewPhoto = async (pesquisa: string[]) =>
    {
      let imageTemp;
      const photos: IHits[] = [];

      for(let i = 0; i < pesquisa.length; i++){
        imageTemp = await getPhoto(pesquisa[i]);
        if(imageTemp!==null){
          photos.push(imageTemp);
        }// VERIFICAR SE FOR NULL, SETAR UMA IMAGEM PADRÃO
      }

      setImagesUrl(photos)
      console.log(photos);
    }

    getNewPhoto(["london sightseeing", "paris sightseeing", "rome sightseeing", "prague sightseeing", "amsterdam sightseeing"]);

  }, []);
  
  return (
    <div>
      <Head>
        <title>WorldTrip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/airplane.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <Navbar />
        <Banner bg="Europa.png" text="Europa" />
        <Flex h={80} justifyContent="center" alignItems={"center"} bg="white">
          <Stack direction={'row'}
            justifyContent="center"
            alignItems="center"
            spacing={'45px'}
          >
            <Show above='sm'>
              <Text mt={'10%'} pr={12} color='dark.headtext' w={'600px'} fontSize='24'>
                A Europa é, por convenção, um dos seis continentes do
                mundo. Compreendendo a península ocidental da Eurásia,
                a Europa geralmente divide-se da Ásia a leste pela
                divisória de águas dos montes Urais, o rio Ural, o
                mar Cáspio, o Cáucaso, e o mar Negro a sudeste
              </Text>
              <Stack justifyContent="center" alignItems={"center"} mt={10}>
                <Text as='b' color='highlight' fontSize='48'>
                  50
                </Text>
                <Text as='b' color='dark.headtext'>
                  países
                </Text>
              </Stack>
              <Stack justifyContent="center" alignItems={"center"} >
                <Text as='b' color='highlight' fontSize='48'>
                  60
                </Text>
                <Text as='b' color='dark.headtext'>
                  línguas
                </Text>
              </Stack>
              <Stack justifyContent="center" alignItems={"center"} >
                <Text as='b' color='highlight' fontSize='48'>
                  27
                </Text>
                <Text as='b' color='dark.headtext'>
                  cidades +100
                </Text>
              </Stack>
            </Show>
          </Stack>

          <Stack direction={'column'}
            justifyContent="center"
            alignItems="center"
          >

            <Show below='sm'>
              <Text justifyContent="space-between" color='dark.headtext' w={'300px'} fontSize='14' pb={30}>
                A Europa é, por convenção, um dos seis continentes do
                mundo. Compreendendo a península ocidental da Eurásia,
                a Europa geralmente divide-se da Ásia a leste pela
                divisória de águas dos montes Urais, o rio Ural, o
                mar Cáspio, o Cáucaso, e o mar Negro a sudeste
              </Text>
              <Stack direction={'row'} spacing={'40px'}>
                <Stack justifyContent="center" alignItems={"center"} >
                  <Text as='b' color='highlight' fontSize='32'>
                    50
                  </Text>
                  <Text color='dark.headtext'>
                    países
                  </Text>
                </Stack>
                <Stack justifyContent="center" alignItems={"center"} >
                  <Text as='b' color='highlight' fontSize='32'>
                    60
                  </Text>
                  <Text color='dark.headtext'>
                    línguas
                  </Text>
                </Stack>
                <Stack justifyContent="center" alignItems={"center"} >
                  <Text as='b' color='highlight' fontSize='32'>
                    27
                  </Text>
                  <Text color='dark.headtext' >
                    cidades +100
                  </Text>
                </Stack>
              </Stack>
            </Show>
          </Stack>
          <Image m={1} src='/icon_Info.png' w={[3, 4]} pt={[240, 20]} />
        </Flex>
        
        <Text color='dark.headtext' fontSize='36'  ml='10%' mt='5%' mb='5%'>Cidades +100</Text>

        {imagesUrl !== null && imagesUrl !== undefined &&( 
          <>
            <Grid mb = {20} templateColumns={['repeat(1, 1fr)', 'repeat(2, 1fr)', 'repeat(3, 1fr)', 'repeat(4, 1fr)']} gap={6} ml='10%' mr='10%'>
              <Card_cidades 
                bg={imagesUrl[0].hits[Math.floor(Math.random() * imagesUrl[0].hits.length)].webformatURL}
                title='Londres' 
                text='Reino Unido' 
                flag ='https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/United-kingdom_flag_icon_round.svg/2048px-United-kingdom_flag_icon_round.svg.png'
              />
              <Card_cidades 
                bg={imagesUrl[1].hits[Math.floor(Math.random() * imagesUrl[1].hits.length)].webformatURL} 
                title='Paris' 
                text='França' 
                flag ='https://cdn-icons-png.flaticon.com/512/197/197560.png'
              />
              <Card_cidades 
                bg={imagesUrl[2].hits[Math.floor(Math.random() * imagesUrl[2].hits.length)].webformatURL} 
                title='Roma' 
                text='Itália' 
                flag ='https://media.istockphoto.com/id/690489086/vector/italian-flag.jpg?s=612x612&w=0&k=20&c=kWZWChm94M--bl4uZgmY-tt-OuJQUvt1ujDp0OWSDp8='
              />
              <Card_cidades 
                bg={imagesUrl[3].hits[Math.floor(Math.random() * imagesUrl[3].hits.length)].webformatURL} 
                title='Praga' 
                text='República Tcheca' 
                flag ='https://media.istockphoto.com/id/894491752/vector/czech-republic-flag-vector-round-flat-icon.jpg?s=170667a&w=0&k=20&c=VaFj9bAOkeNKoL4IHPqVAKg-WR9X5zU91HoiBYQfrDg='
              />
              <Card_cidades 
                bg={imagesUrl[4].hits[Math.floor(Math.random() * imagesUrl[4].hits.length)].webformatURL} 
                title='Amsterdã' 
                text='Holanda' 
                flag ='https://cdn-icons-png.flaticon.com/512/323/323275.png'
              />
            </Grid>
          </>
        )}
      </main>
    </div>
  )
}