import { Box, Image, Text, Stack } from '@chakra-ui/react'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Travel_types } from '../../components/Travel_types'
import Navbar_home from '../../components/Navbar_home'
import { Banner } from '../../components/Banner_home'
import getPhoto from '../services/axios'

import { Swiper, SwiperSlide } from 'swiper/react'
import SwiperCore, { Navigation, Pagination } from 'swiper'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'

SwiperCore.use([Navigation, Pagination])

type IHit = {
  webformatURL: string;
  likes?: number;
}

type IHits = {
  hits: IHit[];
  total: number;
  totalHits: number;
}


export default function Home()
{
  const [imagesUrl, setImagesUrl] = useState<IHits[] | null>();

  useEffect(() =>
  {
    const getNewPhoto = async (pesquisa: string[]) =>
    {
      let imageTemp;
      const photos: IHits[] = [];

      for(let i = 0; i < pesquisa.length; i++){
        imageTemp = await getPhoto(pesquisa[i]);
        if(imageTemp!==null){
          photos.push(imageTemp);
        }// VERIFICAR SE FOR NULL, SETAR UMA IMAGEM PADRÃO
      }

      setImagesUrl(photos)
      console.log(photos);
    }

    getNewPhoto(["europe","america","asia"]);

  }, []);

  return (
    <div>
      <Head>
        <title>WorldTrip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/airplane.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>

      <main>
        <Navbar_home />
        <Banner bg={["Banner_mobile.png", "Banner.png"]} />
        <Travel_types />
        <Stack justifyContent="center"
          alignItems="center"
          pt={['13vh', '5']}
          color={"dark.headtext"}
          fontSize={['20', '36']}
          >
             <Image src='Divider.png' w={['', '20']}/>
          <Text
          >Vamos nessa?
          </Text>
          <Text
          >Então escolha seu continente
          </Text>
        </Stack>
        <Box
          pt={[5, 0]}
          pb={[0, 5]}
          margin={[0, 10]}
        >
          <Swiper
            modules={[Navigation, Pagination]}
            navigation
            pagination={{ clickable: true }}
            style={{
              "--swiper-pagination-color": "#FFBA08",
              "--swiper-navigation-color": "#FFBA08",
            }}
          >
            <SwiperSlide >
              { imagesUrl !== null && imagesUrl !== undefined &&( 
              <><Image src={imagesUrl[0].hits[Math.floor(Math.random() * imagesUrl[0].hits.length)].webformatURL} h={["30vh","60vh"]} w={'100%'} /></>
            )}

            </SwiperSlide>
            <SwiperSlide>
            { imagesUrl !== null && imagesUrl !== undefined &&( 
              <><Image src={imagesUrl[1].hits[Math.floor(Math.random() * imagesUrl[1].hits.length)].webformatURL} h={["30vh","60vh"]} w={'100%'} /></>
            )}
            </SwiperSlide>
            <SwiperSlide>
            { imagesUrl !== null && imagesUrl !== undefined &&( 
              <><Image src={imagesUrl[2].hits[Math.floor(Math.random() * imagesUrl[2].hits.length)].webformatURL} h={["30vh","60vh"]} w={'100%'} /></>
            )} {/* A maior imagem define a altura de todo o Swiper*/}
            </SwiperSlide>
          </Swiper>
        </Box>

      </main>
    </div>
  )
}
