import { Box, Flex, Input, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

export default function Home() {
  const [texto, setTexto] = useState('')

  return (
    <div>
      <Head>
        <title>WorldTrip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      
      <main>
        <Flex h={"100vh"} justifyContent="center" alignItems={"center"} bg="lightblue">
          <Box bg="whiteAlpha.400" borderRadius="xl" padding={"10"}>
            <Text bg="highlight">
              {texto}{texto}{texto}
            </Text>
            <Input 
              type={'text'}
              onChange={(event) => setTexto(event.target.value)}
            ></Input>
          </Box>
        </Flex>  
      </main>
    </div>
  )
}
